#GENERAL
general {
	disable_loading_bar = fase
	no_fade_in = false
	no_fade_out = false
	hide_cursor = true
	grace = 0
}
#BACKGROUND
background {
	monitor =
	path = /tmp/fundo.png
	blur_passes = 3
	contrast = 1
	brightness = 0.7
	vibrancy = 1
	vibrancy_darkness = 0
}
#DATA
label {
	monitor =
	text = cmd[update:1000] echo "$(LC_TIME=pt_BR.UTF-8 date +"%A, %d de %B")"
	color = rgba(242, 243, 244, 0.75)
	font_size = 22
	font_family = Noto San JP,Symbols Nerd Font Mono
	position = 0, 300
	halign = center
	valign = center
}
#HORA
label {
	monitor = 
	text = cmd[update:1000] echo "$(date +"%-I:%M")"
	color = rgba(242, 243, 244, 0.75)
	font_size = 95
	font_family = Noto San JP,Symbols Nerd Font Mono
	position = 0, 200
	halign = center
	valign = center
}
#EU
label {
	monitor =
	text = cmd[update:1000] echo "$(whoami)"
	color = rgb(255,255,255)
	font_size = 18
	font_family = Noto San JP,Symbols Nerd Font Mono
	position = 0, 0
	halign = center
	valign = center
}
#INPUT FIELD
input-field {
	monitor =
	size = 250, 60
	outline_thickness = 2
	dots_size = 0.2 
	dots_spacing = 0.35 
	dots_center = true
	outer_color = rgba(255,255,255,0.2)
	inner_color = rgba(255,255,255,0.1)
	font_color = rgb(255,255,255)
	fade_on_empty = false
	rounding = -1
	check_color = rgb(204, 136, 34)
	placeholder_text = Senha
	hide_input = false
	position = 0, -100
	halign = center
	valign = center
}
#MUSICA
label {
	monitor =
	text = cmd[update:1000] echo "$(sh ~/.config/dotConfig/scripts/musica atual)" 
	color = rgba(255, 255, 255, 0.6)
	font_size = 14
	font_family = Play
	position = 0, 50
	halign = center
	valign = bottom
}
